name: Publish release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0

      # Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      # Make the Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # Run the gradle task
      - name: Run gradle task
        run: ./gradlew publishReleasePublicationToHangar -Pio.papermc.hangar-publish-plugin.default-api-key=${{ secrets.HANGAR_API_KEY }}
